name: Build and Push Docker Image

on:
  push:
    branches:
      - v0.1.0  # Or specify any branch you'd like to trigger the build on
        #    paths:
        #- 'Dockerfile'
        #- 'SoC-odoo-community-17.0.20240313/**'
        #- 'entrypoint.sh'
        #- 'odoo.conf'

jobs:
  build:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: login to docker hub
          id: docker-hub
          env:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}
          run: |
            docker login -u $username -p $password 
        - name: build the docker image
          id: build-docker-image
          run: |
            ls -la 
            docker build . -f Dockerfile -t weihangang/my-test-repo:test .
        - name: push the docker image
          id: push-docker-image
          run: docker push ${{secrets.DOCKERHUB_USERNAME}}/weihangang/my-test-repo:test .
