name: Build and Push Docker Image

on:
  push:
    branches:
      - v*  # Specify the branch to trigger the build
    paths:
      - Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      
      - name: Extract date
        id: vars
        run: echo "IMAGE_TAG=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_ENV
      
      - name: Build the Docker image
        run: |
          ls -la
          docker build . -f Dockerfile -t weihangang/my-test-repo:${{ env.IMAGE_TAG }}
      
      - name: Push the Docker image
        run: |
          docker push weihangang/my-test-repo:${{ env.IMAGE_TAG }}
