name: Build and Push Docker Image

on:
  push:
    branches:
      - v0.1.0  # Specify the branch to trigger the build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      
      - name: Build the Docker image
        run: |
          ls -la
          docker build . -f Dockerfile -t weihangang/my-test-repo:test
      
      - name: Push the Docker image
        run: |
          docker push weihangang/my-test-repo:test
