name: Code-analyse
on:
  workflow_dispatch:
  push:
    branches: 
      - "v*"
  pull_request:
    types: 
      - opened
      - synchronized
      - reopened
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        run: |
          TAG=$(basename ${GITHUB_REF})
          echo "TAG=$TAG" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ env.TAG }}
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
   
   
